version: '3.8'

services:
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - mongo:/data/db
    networks:
      - local_network
    ports:
      - 27017:27017
    restart: always
  
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - local_network
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306
    depends_on:
      - mongodb
    restart: always
    

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8001:80
    networks:
      - local_network
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      - mysql
    restart: always
    


  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
    networks:
      - local_network
    ports:
      - 8002:8081
    depends_on:
      - phpmyadmin
    links:
      - mongodb
    restart: always

  cache:
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data
    

volumes:
  mysql:
    driver: local
  mongo:
    driver: local
  cache:
    driver: local

networks:
  local_network:
    name: "local_network"
