version: '3.8'

services:
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ./dbData/mongo:/data/db
    networks:
      - local_network
    ports:
      - 27017:27017
  

  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - local_network
    volumes:
      - ./dbData/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    depends_on:
      - mongodb


  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
    networks:
      - local_network
    ports:
      - 8002:8081
    depends_on:
      - mysql


  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8001:80
    networks:
      - local_network
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      - mongo-express

networks:
  local_network:
    name: "local_network"
